driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['.', '/home/vagrant/supermarket']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.2

platforms:
  - name: ubuntu-10.04
    run_list: apt::default
  - name: centos-5.10

suites:
  - name: default
    run_list: omnibus-supermarket::build_package
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/supermarket
        install_dir: /opt/supermarket
        log_level: debug
