driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 4096
  synced_folders:
    - ['..', '/home/vagrant/supermarket']

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14

platforms:
  # for Ubuntu, only need earliest supported version for build
  # testing occurs on earliest supported and later in a different kitchen
  - name: ubuntu-16.04
  - name: centos-6
  - name: centos-7
  - name: centos-8

suites:
  - name: default
    attributes:
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_user_home: /home/vagrant
        build_dir: /home/vagrant/supermarket/omnibus
        install_dir: /opt/supermarket
    run_list:
      - supermarket-builder
