# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

# require File.expand_path("../src/supermarket/config/application", __dir__)
require 'sprockets/rails/task'

# Supermarket::Application.load_tasks

