require:
  - chefstyle
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0.3
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
Style/SymbolArray:
  EnforcedStyle: brackets
Chef/Ruby/UnlessDefinedRequire:
  Enabled: false
