source "https://rubygems.org"

# Declare your gem's dependencies in fieri.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
group :development, :test do
  gem "chefstyle"
  gem "pry"
  gem "rspec-rails", "~> 5.1"
  gem "rubocop-rails", require: false
  gem "sqlite3"
  gem "webmock"
  gem "mixlib-shellout", "~> 3.2"
  gem "mixlib-archive", ">= 0.4", "< 2.0"
end
