name             'supermarket'
maintainer       'Chef Supermarket Team'
maintainer_email 'supermarket@getchef.com'
license          'apache2'
description      'Installs/Configures supermarket in an Omnibus installation'
long_description 'Installs/Configures supermarket in an Omnibus installation'
version          '1.0.0'
depends          'enterprise'
depends          'runit'
depends          'sysctl'
