---
driver:
  name: vagrant
  synced_folders:
    - ['../../pkg', '/tmp/packages', 'create: true, type: :rsync']

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-10.04
  - name: centos-5.10

suites:
  - name: default
    run_list:
      - recipe[omnibus-supermarket::cookbook_test]
    attributes:
      supermarket:
        test:
          deb_package_path: false
          rpm_package_path: false
