#!/bin/sh

migrate_and_seed_the_db() {
  . "{{pkg.path}}/dist/supermarket/runtime_environment.sh"

  cd "${APP_RUN_DIR}" || exit

  bin/rake db:abort_if_pending_migrations 2>&1

  if [ $? -eq 0 ]
  then
    echo "Schema up-to-date. Continuing with service startup."
  else
    echo "Schema migrations pending. Running migrations & seeds."
    exec bin/rake --trace db:migrate db:seed 2>&1
  fi
}

if [ "${DB_MIGRATE:=false}" = "true" ]
then
  echo "I'm responsible for doing the database schema migrations."
  migrate_and_seed_the_db
else
  echo "I'm not responsible for the database schema."
fi
