#!/bin/sh
exec 2>&1

. "{{pkg.path}}/dist/runtime_environment.sh"

cd {{pkg.svc_var_path}}
ln -sf {{pkg.svc_config_path}}/env.production {{pkg.svc_var_path}}/.env

migrate_and_seed_the_db() {
  rake_opts="--rakefile ${APP_RUN_DIR}/Rakefile"
  rake ${rake_opts} db:abort_if_pending_migrations 2>&1

  if [ $? -eq 0 ]
  then
    echo "Schema up-to-date. Continuing with service startup."
  else
    echo "Schema migrations pending. Running migrations & seeds."
    exec rake ${rake_opts} --trace db:migrate db:seed 2>&1
  fi
}

if [ "${DB_MIGRATE:=false}" = "true" ]
then
  echo "I'm responsible for doing the database schema migrations."
  migrate_and_seed_the_db
else
  echo "I'm not responsible for the database schema."
fi
