#!/bin/sh
exec 2>&1

. "{{pkg.path}}/dist/runtime_environment.sh"

cd {{pkg.svc_var_path}}

web_command="unicorn -E production \
    -c {{pkg.svc_config_path}}/unicorn.rb \
    ${APP_RUN_DIR}/config.ru"

workers_command="sidekiq \
    --require ${APP_RUN_DIR} \
    --concurrency {{cfg.sidekiq.concurrency}} \
    --environment production \
    --timeout {{cfg.sidekiq.timeout}}"


echo "FLAVOR: ${FLAVOR:=web}"

case $FLAVOR in
  "web")
    echo "We're webby!"
    service_command=$web_command;;
  "workers")
    echo "We're workers!"
    service_command=$workers_command;;
  *)
    echo "Sorry. FLAVOR env var must be 'web' or 'workers'. Defaults to 'web'."
    exit 1;;
esac

if [ "$(whoami)" = "root" ]; then
  exec chpst \
    -U hab:hab \
    -u hab:hab \
    ${service_command}
else
  exec ${service_command}
fi
