require:
  - chefstyle
  - rubocop-rails
Rails:
  Enabled: true
AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7
  Exclude:
    - db/**/*
    - engines/**/*
    - vendor/**/*
    - node_modules/**/*
Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
Lint/UselessAssignment:
  Exclude:
    - config.rb
Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/setup.rake
    - lib/tasks/spec/javascripts.rake
Rails/SkipsModelValidations:
  Whitelist:
    - increment_counter
    - touch
Style/SymbolArray:
  EnforcedStyle: brackets
Rails/HttpStatus:
  Enabled: true
  EnforcedStyle: numeric
Rails/HasManyOrHasOneDependent:
  Enabled: false