version: '2'
services:
  db:
    image: postgres:13.4
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${USER}
  cache:
    image: redis:6.2.5
    ports:
      - "127.0.0.1:6379:6379"
