source "https://rubygems.org"

gem "fieri", path: "engines/fieri"
gem "rails", "~> 7.0.2"
gem "omniauth", "~> 2.1.0"
gem "omniauth-chef-oauth2"
gem "omniauth-github", "~> 2.0.0"
gem "omniauth-oauth2", "~> 1.7.2"
gem "omniauth-rails_csrf_protection"
gem "coderay" # markdown doc - syntax highlighting

gem "sidekiq", "~> 6.4"
gem "sidekiq-cron"

gem "aws-sdk-s3"
gem "chef", "~> 17.10", require: false
gem "compass-rails"
gem "ddtrace", "1.0.0", require: false
gem "dotenv"
gem "ffi-libarchive"
gem "foreman"
gem "honeycomb-beeline"
gem "html_truncator"
gem "jbuilder"
gem "kaminari"
gem "mixlib-authentication", "~> 3.0"
gem "nokogiri"
gem "octokit", "~> 4.22", require: false # 4.16+ fixes deprecations in auth
gem "pg"
gem "pg_search"
gem "premailer-rails", group: [:development, :production]
gem "pundit"
gem "rb-readline"
gem "redcarpet" # markdown parsing
gem "redis-rails"
gem "rinku", require: "rails_rinku"
gem "rollout"
gem "sass-globbing"
gem "sass-rails"
gem "sentry-raven", require: false
gem "sitemap_generator"
gem "statsd-ruby"
gem "tomlrb"
# gem "uglifier"
gem "unicorn"
gem "unicorn-rails"
gem "utf8-cleaner"
gem "validate_url"
gem "dry-struct", "~>1.4"
gem "yajl-ruby"
gem "tzinfo-data", "~> 1.2022"

gem "listen"
gem "cookstyle", "~> 7.32.1"
gem "kt-paperclip"
gem "net-smtp", require: false
# gem "sprockets"
# gem "libv8-node"
# gem "mini_racer"

group :asset do
  gem 'uglifier'
  gem 'execjs'
end

group :doc do
  gem "yard", require: false
end

group :development do
  gem "guard"
  gem "guard-rspec", require: false
  gem "guard-rubocop", require: false
  gem "license_finder"
  gem "spring"
  gem "spring-commands-rspec"
  gem "brakeman"
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "poltergeist"
  gem "rails-controller-testing"
  gem "shoulda-matchers"
  gem "vcr", require: false
  gem "webmock", require: false
  gem "puma"
  gem "simplecov", require: false
end

group :development, :test do
  gem "chefstyle", "~> 2.2.2"
  gem "factory_bot_rails", require: false
  gem "faker"
  gem "launchy"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop-rails"
  gem "letter_opener_web", "~> 2.0"

  # Pinned to be greater than or equal to 1.0.0.pre because the gems were prior
  # to 1.0.0 release when added
  gem "and_feathers", ">= 1.0.0.pre", require: false
  gem "and_feathers-gzipped_tarball", ">= 1.0.0.pre", require: false
end