---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.33.33' }]
  synced_folders:
    - ['../../pkg', '/tmp/packages', 'create: true, type: :rsync']

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[omnibus-supermarket::cookbook_test]
    attributes:
      supermarket:
        test:
          deb_package_path: <%= ENV['SUPERMARKET_DEB'] || false %>
          rpm_package_path: <%= ENV['SUPERMARKET_RPM'] || false %>
        ingredient_config:
