---
driver:
  name: vagrant
  network:
    - ['private_network', type: 'dhcp']
  synced_folders:
    - ['.', '/tmp/omnibus-supermarket-cookbook']
    - ['../../pkg', '/tmp/packages', 'create: true, type: :rsync']

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept-no-persist
    ssl_verify_mode: verify_peer

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: centos-7
  - name: centos-8
  - name: amazonlinux-2

suites:
  - name: default
    run_list:
      - recipe[omnibus-supermarket::cookbook_test]
    attributes:
      supermarket:
        test:
          version_to_install: <%= ENV['VERSION_TO_INSTALL'] || false %>
        ingredient_config:
