name             'omnibus-supermarket'
maintainer       'Chef Supermarket Team'
maintainer_email 'supermarket@getchef.com'
license          'apache2'
description      'Installs/Configures supermarket in an Omnibus installation'
long_description 'Installs/Configures supermarket in an Omnibus installation'
version          '1.0.0'
depends          'enterprise'
depends          'nginx'
depends          'omnibus'
depends          'runit'
depends          'sysctl'
depends          'unicorn'
depends          'openssl', '~> 4.4.0'
