name             'omnibus-supermarket'
maintainer       'Chef Supermarket Team'
maintainer_email 'supermarket@chef.io'
license          'Apache-2.0'
description      'Installs/Configures supermarket in an Omnibus installation'
long_description 'Installs/Configures supermarket in an Omnibus installation'
version          '1.1.1'

depends          'enterprise'
depends          'runit', '>= 3.0.3'
depends          'sysctl', '>= 0.10.1'
depends          'unicorn'
depends          'openssl', '>= 6.1.1'
