development:
  adapter: postgresql
  database: supermarket_development
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>
  pool: 30
  # Uncomment the following line only if you encounter GSSAPI encryption issues
  # This is typically needed on specific operating systems like macOS Tahoe or later
  # Leave commented by default unless experiencing PostgreSQL connection problems
  # gssencmode: "disable"

test:
  adapter: postgresql
  database: supermarket_test
  host: <%= ENV['POSTGRES_IP'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>

production:
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  adapter: postgresql
  database: supermarket_production
